version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/

hooks:
  BeforeInstall:
    - location: ./scripts/install_dependencies.sh
      timeout: 300
      useras: ec2-user      
  ApplicationStop:
    - location: ./scripts/stop_server.sh
      timeout: 300
      useras: ec2-user 
  Install:
    - location: ./scripts/install_container.sh
      timeout: 300
      useras: ec2-user
  
  ApplicationStart:    
    - location: ./scripts/start_app.sh
      timeout: 300
      useras: ec2-user 
  ValidateService:
    - location: ./scripts/validate_app.sh
      timeout: 300
      useras: ec2-user
      
