version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html/

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
     
    
  ApplicationStart:    
    - location: start_server.sh
      timeout: 300

