version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
    
  ApplicationStart:    
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
