version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/

hooks:
  BeforeInstall:
    - location: ./Scripts/install_dependencies.sh
      timeout: 300
      
  ApplicationStop:
    - location: ./Scripts/stop_server.sh
      timeout: 300
     
    
  ApplicationStart:    
    - location: ./Scripts/start_server.sh
      timeout: 300

