version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/
hooks:
 
  AfterInstall:
    - location: scripts/configure_nginx
      timeout: 300
      runas: ec2-user   
  ApplicationStart:    
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/health_check
      timeout: 60
      runas: ec2-user  
